sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t eltriphop/docker-react .

script:
  - docker run -e CI=true eltriphop/docker-react npm run test -- --coverage
  