sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t eltriphop/docker-react .

script:
  - docker run -e CI=true eltriphop/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-593708562603"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"